# Generated by Django 3.0.4 on 2020-05-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200519_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomdetails',
            name='room_type',
            field=models.IntegerField(choices=[(1, 'direct'), (2, 'group')], default=1),
        ),
    ]
